name: Events Demo 1
on:
  pull_request:
    # we can use activity types to control an event
    types:
      - opened
  workflow_dispatch:
  push:
    # we can also use event filters to control the events
    branches:
      - main # main
      - 'dev-*' # Any character - examples: dev-new, dev-this-is-new
      - 'feature/**' # Any chars including more "/" - examples: feature/new, feature/new/button
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
